### PR TITLE
Update toolchain

### PR DESCRIPTION
**Pull request by tzerrell**
Match the toolchain version from https://github.com/risc0/risc0/pull/320

### CODE REVIEW

**Comment by flaub** [comment]
Do we also need to bump any git commit revs?

**Comment by tzerrell** [comment]
> Do we also need to bump any git commit revs?

No revs to update, this repo always points to HEAD. Example line: https://github.com/risc0/risc0-rust-starter/blob/cf6e6d306b88599231bc95a3a0d13f4b530cf6e8/methods/Cargo.toml#LL7-L7C61

**Comment by flaub** [comment]
Oh interesting, I was assuming we'd point to a specific version. It might make sense to pin it (similar to how we pin to a specific crate version).

**Comment by tzerrell** [comment]
We certainly could pin a specific commit -- that would prevent temporary breaks like the one we're addressing in this PR (although since we don't commit .lock files in this repo, this specific case would be broken for a different reason if pinned to a specific risc0 commit).

My interpretation of the discussion in https://github.com/risc0/risc0-rust-starter/pull/24 was that we wanted to be on actual HEAD not a pinned commit -- that this repo should always get the latest changes, and while that "shouldn't" introduce breaks, we nevertheless do come and fix any breaking changes that do occur by staying at HEAD.

But a pinned commit that we update more frequently than we push versions is certainly a reasonable compromise between stability + stagnation vs. bleeding edge + surprise bugs.

**Comment by tzerrell** [comment]
Deprecated for https://github.com/risc0/risc0-rust-starter/pull/27

**Pull request closed without merging**
