### PR TITLE
Update readme quick start instructions

### PR DESCRIPTION
**Pull request by choongng**
`rust-src` appears to be required to build.

### CODE REVIEW

**Review by flaub — APPROVED** [review]

**Comment by flaub** [comment]
Actually, I think if we put a `rust-toolchain` file (like we have in our other repositories), then cargo will automatically install this for us.

**Comment by flaub** [comment]
See: https://github.com/risc0/battleship-example/blob/main/rust-toolchain

**Comment by choongng** [comment]
Hmm, there already is such a file, and it does list rust-src, but for some reason rust-src didn't install: https://github.com/risc0/risc0-rust-starter/blob/main/rust-toolchain

**Comment by choongng** [comment]
It turns out the manual override step was the problem, going straight to cargo run works fine.

**Pull request merged**
